language: java

matrix:
  include:
    ## https://docs.travis-ci.com/user/reference/trusty/
    ## container-based trusty should be working
    ## has newer Maven and JDK
    - os: linux
      sudo: false
      dist: trusty
      jdk: oraclejdk8
      install: true
      env: FAILURES_ALLOWED=false
    ## OpenJDK should work too
    - os: linux
      sudo: false
      dist: trusty
      jdk: openjdk8
      install: true
      env: FAILURES_ALLOWED=false
    ## old Precise-Images do not contain proper JDK, as 1.8.0_u40 is minimum requirement
    ## before 1.8.0_40 will fail compiling since javafx-maven-plugin 8.8.0
    ## has older Maven and JDK
    - os: linux
      sudo: false
      dist: precise
      jdk: oraclejdk8
      env: FAILURES_ALLOWED=true
    - os: osx
      osx_image: xcode8
      env: FAILURES_ALLOWED=false
  allow_failures:
    - env: FAILURES_ALLOWED=true

## maven-invoker-plugin is called after deploying javafx-maven-plugin into local repository, so change default-test-call to "install" (because its called at that maven-phase)
script:
  - mvn install -B

branches:
  only:
  - master

notifications:
  email: false
